name = "caveful_games/table_helper"
version = "0.1.0"
description = "A collection of helpful table utility functions extending TableUtil from RbxUtil for luau"
authors = ["jiwonz <me@jiwonz.kr>", "Stephen Leitnick"]
repository = "https://github.com/CavefulGames/table-helper-luau"
license = "MIT"
includes = ["src/**", "LICENSE", "pesde.toml", "README.md"]

[target]
environment = "luau"
lib = "src/lib/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dev_dependencies]
luau_check = { name = "jiwonz/luau_check", version = "^0.3.5", target = "lune" }
